spring.application.name=rx-donation-backend
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/rxdonation_db
spring.datasource.username=anant-saini
spring.datasource.password=HarryPotter@123

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Handle NoHandlerFoundException
spring.mvc.throw-exception-if-no-handler-found=true
spring.resources.add-mappings=false

# JWT Configuration
app.jwt.secret=your-super-secret-key-that-must-be-at-least-256-bits-for-HS256
app.jwt.expiration-ms=10800000
app.jwt.refresh-expiration-ms=604800000